[package]
name = "astroport"
version = "5.7.0"
authors = ["Astroport"]
edition = "2021"
description = "Common Astroport types, queriers and other utils"
license = "Apache-2.0"
repository = "https://github.com/astroport-fi/astroport"
homepage = "https://astroport.fi"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]

[dependencies]
cw20 = "2.0"
cosmwasm-std.workspace = true
cw-storage-plus.workspace = true
itertools.workspace = true
cosmwasm-schema.workspace = true
cw-utils.workspace = true
cw-asset = "4.0"

[dev-dependencies]
test-case = "3.1.0"
